# Generated by Django 5.2.17 on 2026-10-01 23:10

import django.core.serializers.json
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroupsExampleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(default='car', max_length=255)),
                ('doors', models.PositiveSmallIntegerField(default=0)),
                ('fuel', models.CharField(blank=True, default='', max_length=255)),
                ('battery_kwh', models.PositiveIntegerField(default=0)),
                ('gears', models.PositiveSmallIntegerField(default=0)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
